### ISSUE TITLE
New release to enable log level debug

### ISSUE THREAD

**Issue by jeurrutia** [rebuy-de/exporter-merger#12]
Hi,

I've seen there is no new release to enable/disable the log level. Is it planned to create a new release to add the feature?

Thanks

**Comment by svenwltr** [comment]
Hello @jeurrutia.

Here you go: https://github.com/rebuy-de/exporter-merger/releases/tag/v0.4.0

**Comment by jeurrutia** [comment]
I've seen the image build failed: https://quay.io/repository/rebuy/exporter-merger?tab=info

Any ideas on this?

Thanks

**Comment by svenwltr** [comment]
Hello @jeurrutia.

Sorry for the late response. The Quay image had some permission problems. The image is available now.

**Comment by jeurrutia** [comment]
Ok. Thank you very much @svenwltr
